ems-project/EMSClientHelperBundle

EMSBackendBridgeBundle/README.md
EMSLanguageSelectionBundle/Controller/LanguageController.php
EMSLanguageSelectionBundle/DependencyInjection/Configuration.php
EMSLanguageSelectionBundle/DependencyInjection/EMSLanguageSelectionExtension.php
EMSLanguageSelectionBundle/EMSLanguageSelectionBundle.php
EMSLanguageSelectionBundle/EventSubscriber/KernelSubscriber.php
EMSLanguageSelectionBundle/README.md
EMSLanguageSelectionBundle/Resources/config/backendBridgeServices.xml
EMSLanguageSelectionBundle/Resources/config/services.xml
EMSLanguageSelectionBundle/Resources/views/language_selection.html.twig
EMSLanguageSelectionBundle/Service/LanguageService.php
EMSLanguageSelectionBundle/Tests/Controller/DefaultControllerTest.php
EMSTwigListBundle/README.md
EMSTwigListBundle/Resources/config/routing.yml
README.md

Based on David Mattei his work on other project

Bundle for language selection page

---

EMSRoutingBundle/DependencyInjection/Configuration.php
EMSRoutingBundle/DependencyInjection/EMSRoutingExtension.php
EMSRoutingBundle/Resources/config/services.xml
EMSRoutingBundle/Service/RoutingService.php
EMSRoutingBundle/Twig/RoutingExtension.php
EMSRoutingBundle/Twig/RoutingTemplateLoader.php

- twig filter is now emsch_routing and also passing link type
- routing service will catch exceptions
- routing service will generate a correct baseUrl
- improve configuration 'ems_routing.paths' and 'ems_routing.twig_cache'

Improve routing bundle

---

EMSBackendBridgeBundle/Elasticsearch/ClientRequest.php
EMSRoutingBundle/Controller/FileController.php
EMSRoutingBundle/DependencyInjection/Compiler/ClientRequestPass.php
EMSRoutingBundle/DependencyInjection/Compiler/ConfigPass.php
EMSRoutingBundle/DependencyInjection/Configuration.php
EMSRoutingBundle/DependencyInjection/EMSRoutingExtension.php
EMSRoutingBundle/EMSFileInfo.php
EMSRoutingBundle/EMSLink.php
EMSRoutingBundle/EMSRoutingBundle.php
EMSRoutingBundle/Resources/config/routing.yml
EMSRoutingBundle/Resources/config/services.xml
EMSRoutingBundle/Service/FileManager.php
EMSRoutingBundle/Service/RoutingService.php
EMSRoutingBundle/Service/UrlHelperService.php
EMSRoutingBundle/Twig/RoutingExtension.php
EMSRoutingBundle/Twig/TemplateLoader.php
Tests/EMSRoutingBundle/Twig/RoutingExtensionTest.php
composer.json
phpunit.xml.dist

- add test for testing ems link regex
- refactor the configuration
- create a file manager and controller
- implement e-tag response
- fix session lock writing in the controller

File downloading from RoutingBundle

---

EMSBackendBridgeBundle/Service/RequestService.php
EMSRoutingBundle/Service/UrlHelperService.php

- request service current request can be null
- url helper service baseUrl can be null

Fix cache warmup errors

---

DependencyInjection/EMSClientHelperExtension.php
Helper/Request/ExceptionHelper.php
Resources/config/services.xml

It was hardcoded to catalog_template.

---

Helper/Routing/EMSRouter.php
Helper/Routing/RouteConfig.php

Make the custom ems router handle array or paths for each locale
https://symfony.com/blog/new-in-symfony-4-1-internationalized-routing

Improve internationalized routing

---

Helper/Twig/TwigLoader.php

First look at _published_datetime then fallback to
_finalization_datetime

hotfix: template cache invalidation

---

Controller/RouterController.php

The template should return the following json:
{"status": 302, "url": "/test"}
**Twig code:**
{% spaceless %}
{% set data = {"status": 302, "url": "/test"} %}
{% endspaceless %}
{{- data|json_encode|raw -}}
And on the routing set the _controller option to:
**emsch.controller.router::redirect**

feature: improve redirect route

---

Helper/Asset/AssetHelperRuntime.php

After refactor I forgot to touch a file with the hash for checking the
sign. In the old code the checkSign would fail because sha1_file got
called on not existing file.

bugfix: emsch_assets is not switching on update.

---

Helper/Elasticsearch/ClientRequestRuntime.php

Sorry my mistake, thought is was working. But emsch_get is now always taking the first result.
The term on id is missing because I overwrote the bool.
Greetings
David

hotfix: broke emsch_get

---

Helper/Search/QueryBuilder.php
Helper/Search/Search.php
Resources/doc/search.md

make it possible to difine search sort options, to resolve failures

feature add sort options in search config

---

Controller/ApiController.php
Helper/Api/ApiService.php
Helper/Api/Client.php
Resources/config/api.xml

For a better core api integration
- new discard draft method in the client
- api returns a json with the first elasticms server's error message in case of error
- it try to discard the draft in case of error

Better api

---

composer.json
phpstan-baseline.neon
phpstan.neon.dist

|Fixed tickets  ||	
Upgrading phpstan, latest release, highest level. 302 new errors tracked via the new baseline feature

main(stan): upgrade to latest with baseline activated

---

DependencyInjection/Configuration.php
DependencyInjection/EMSClientHelperExtension.php
EventListener/KernelListener.php
Helper/Request/LocaleHelper.php
Resources/config/services.xml

Remove the need to initiate a session and had a parameter to be cookie less (if the locale is not bind in a cookie)

bug[session]: Bind locale in cookie and new bind_locale bundle paramater

---

Controller/RouterController.php
Resources/config/routing.xml

Allow to define a route to an asset using the router controller

feat[router]: route to asset

---

Command/HealthCheckCommand.php
EventListener/KernelListener.php
Helper/Routing/Route.php
phpstan-baseline.neon

|Bug fix?       |no|
|New feature?   |yes|	
|Fixed tickets  |no|	
Fixed deprecation in kernelEventListener
And add option for route conditions:
https://symfony.com/doc/4.1/routing/conditions.html

feat(routing): add route condition

---

Helper/Search/QueryBuilder.php
Helper/Search/Search.php
phpstan-baseline.neon

Add the possibility to add sorting on score
|Bug fix?       |no|
|New feature?   |yes|	
|Fixed tickets  |no|

feat: search score sorting

---

Controller/UserApi/FileController.php
Controller/UserApi/TestController.php
Exception/UserApiResponseException.php
Helper/UserApi/FileService.php
Helper/UserApi/TestService.php
Resources/config/routing/user_api.xml
Resources/config/user_api.xml

release: 3.3.3

---

Helper/Search/Filter.php
phpstan-baseline.neon

Co-authored-by: David Mattei <david.mattei@smals.be>
|Bug fix?       |yes|
|New feature?   |no|	
|Fixed tickets  |no|

release: 3.3.4

---

EventListener/RedirectListener.php
Helper/Api/ApiService.php
Helper/Elasticsearch/ClientRequest.php
phpstan-baseline.neon

Release 3.3.5

---

DependencyInjection/EMSClientHelperExtension.php

fix: update logger to elastica

---

DependencyInjection/EMSClientHelperExtension.php

fix: missing mapping service

---

Command/HealthCheckCommand.php
Helper/Search/Filter.php
Resources/doc/search.md
phpstan-baseline.neon

feat: search filter date_version

---

Helper/Search/Filter.php

feat: empty query in setChoices

---

composer.json

https://github.com/ems-project/EMSClientHelperBundle/issues/143

chore: twig 2.14

---

Helper/Search/QueryBuilder.php

chore: phpstan issue

---

Helper/Elasticsearch/ClientRequest.php
Helper/Search/QueryBuilder.php

Scroll for all content type (index ingonred!)

Release 3.4.1

---

Helper/Elasticsearch/ClientRequest.php
Helper/Environment/EnvironmentHelper.php
Helper/Routing/Router.php
phpstan-baseline.neon

fix: scroll are not sortable, switch the get route to a simple search

---

Helper/Elasticsearch/ClientRequest.php

Depends on https://github.com/ems-project/EMSCommonBundle/pull/199

fix: agg contentType multiple indices

---

src/Helper/ContentType/ContentTypeCollection.php

fix: test that the last update date is a string from the agg query

---

phpstan-baseline.neon

chore: refactor php_stan baseline

---

src/Command/HealthCheckCommand.php
src/Helper/ContentType/ContentTypeCollection.php
src/Helper/ContentType/ContentTypeHelper.php
src/Helper/Elasticsearch/ClientRequest.php
src/Helper/Environment/Environment.php
src/Helper/Routing/Router.php

new environment alias option (default value : environment's name) (if check everywhere, the only last call to getName is to compare the request header)

feat: environment's alias

---

src/Helper/ContentType/ContentTypeHelper.php

When we have no connection we are getting a 500 error. (white page)

fix: contentType helper no connection

---

README.md

|Bug fix?       |+|
|New feature?   |-|	
|BC breaks?     |-|	
|Deprecations?  |-|	
|Fixed tickets  ||

Fix command syntax highlight in readme

---

src/DependencyInjection/Compiler/ClientHelperPass.php
src/Helper/Elasticsearch/ClientRequestRuntime.php

fix: twig emsch_data

---

src/DependencyInjection/Compiler/ClientHelperPass.php
src/Helper/Search/Manager.php

fix: bc break on search results page

---

doc/Twig/filters.md
src/Helper/Routing/Url/Transformer.php

- emsch routing locale context (#243)

release: 3.5.14

---

src/Contracts/Api/ApiClientInterface.php
src/Contracts/Api/ApiServiceInterface.php
src/Contracts/ContentType/ContentTypeInterface.php
src/Contracts/Elasticsearch/ClientRequestInterface.php
src/Contracts/Elasticsearch/ClientRequestManagerInterface.php
src/Contracts/Environment/EnvironmentHelperInterface.php
src/Contracts/Templating/TemplatingInterface.php
src/Helper/Api/ApiService.php
src/Helper/Api/Client.php
src/Helper/ContentType/ContentType.php
src/Helper/Elasticsearch/ClientRequest.php
src/Helper/Elasticsearch/ClientRequestManager.php
src/Helper/Environment/EnvironmentHelper.php
src/Helper/Twig/TwigLoader.php
src/Resources/config/api.xml
src/Resources/config/services.xml

|Bug fix?       ||
|New feature?   ||	
|BC breaks?     ||	
|Deprecations?  ||	
|Fixed tickets  ||	
- add contracts ([#246](https://github.com/ems-project/EMSClientHelperBundle/pull/246))

release 3.5.15

---

src/Contracts/Api/ApiClientInterface.php

fix: missing contract getFormVerification()

---

LICENSE
composer.json

https://github.com/ems-project/maintainers/issues/15

chore: composer and license

---

.github/workflows/commit_quality.yml

https://github.com/ems-project/maintainers/issues/17

ci: Commit Quality

---

.github/workflows/commit_quality.yml
LICENSE
composer.json
phpstan-baseline.neon
src/Contracts/Api/ApiClientInterface.php
src/Contracts/Request/HandlerInterface.php
src/Helper/Request/Handler.php
src/Resources/config/routing.xml

- add contract handler [#252](https://github.com/ems-project/EMSClientHelperBundle/pull/252)
- $results not defined => $results['hits']['total'] is always set to 0 [#253](https://github.com/ems-project/EMSClientHelperBundle/pull/253)
- composer and license [#249](https://github.com/ems-project/EMSClientHelperBundle/pull/249)
- commit quality [#251](https://github.com/ems-project/EMSClientHelperBundle/pull/251)

release: 3.5.16

---

src/Helper/Elasticsearch/ClientRequest.php

build: 3.7.2

---

.github/workflows/code_quality.yml
src/Helper/Elasticsearch/ClientRequest.php

* fix: call lastModified on null
* fix: phpstan

build: 3.7.3

---

src/Command/Local/UploadAssetsCommand.php
src/Helper/Local/LocalHelper.php
src/Resources/config/local.xml

New emsch:local:upload-assets commands in order to zip and upload assets to the elasticms

feat: upload assets local command

---

src/Command/Local/UploadAssetsCommand.php
src/Helper/Local/LocalHelper.php
src/Resources/config/local.xml

- upload assets local command (#269)

build: 3.7.4

---

src/Helper/Request/RequestHelper.php

Allow underscore in route parameters

fix: add underscore in route

---

src/Controller/AssetController.php
src/Resources/config/services.xml

|Bug fix?       |y/n|
Add a hook to directly specify an alias within the request's headers

fix: assets and alias

---

src/Controller/AssetController.php

refactor: better header format name

---

src/Controller/AssetController.php
src/Resources/config/services.xml

- assets and alias (#278)
- better header format name (#280)

build: 3.7.6

---

src/Helper/Search/Search.php

- search index request from request (#282)

build: 3.7.7

---

src/DependencyInjection/EMSClientHelperExtension.php
src/Helper/Routing/Url/Transformer.php
src/Resources/config/routing.xml

refactor: 
- use ems_asset_path to generate asset path (#284)

build: 3.7.8

---

src/DependencyInjection/EMSClientHelperExtension.php
src/Helper/Routing/Url/Transformer.php
src/Resources/config/routing.xml

build: 3.7.9

---

src/Command/Local/AbstractUploadCommand.php
src/Command/Local/FolderUploadCommand.php
src/Command/Local/UploadAssetsCommand.php
src/Helper/Routing/Route.php
src/Resources/config/local.xml

build: 3.7.13

---

doc/environment.md
src/Helper/ContentType/ContentType.php
src/Helper/Environment/Environment.php

feat: remote cluster

---

doc/environment.md
src/Helper/Asset/AssetHelperRuntime.php
src/Helper/ContentType/ContentType.php
src/Helper/Environment/Environment.php
src/Helper/Environment/EnvironmentHelper.php
src/Helper/Routing/Url/Transformer.php
src/Resources/config/routing.xml

build: 3.7.14

---

src/Helper/Environment/EnvironmentHelper.php

cli request may have an active environment

fix: cli request with active environment

---

src/Helper/Environment/EnvironmentHelper.php

build: 3.7.21

---

composer.json
doc/twig.md
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSClientHelperExtension.php
src/Helper/Asset/AssetHelperRuntime.php
src/Helper/Asset/AssetVersionStrategy.php
src/Resources/config/services.xml
src/Twig/HelperExtension.php

emsch_assets_version twig function

feat: version strategy

---

composer.json
doc/twig.md
src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSClientHelperExtension.php
src/Helper/Asset/AssetHelperRuntime.php
src/Helper/Asset/AssetVersionStrategy.php
src/Resources/config/services.xml
src/Twig/HelperExtension.php

build: 3.7.22

---

src/Helper/Asset/AssetHelperRuntime.php

And avoid environment not found exception

fix: ensure that the assets are extracted in revision iframe

---

src/Command/Local/UploadAssetsCommand.php
src/Resources/config/local.xml

fix: upload asets in the local asset folder (if defined)

---

src/Command/Local/UploadAssetsCommand.php
src/Helper/Asset/AssetHelperRuntime.php
src/Resources/config/local.xml

build: 3.7.28

---

doc/routing.md
src/Command/Local/UploadAssetsCommand.php
src/Controller/CacheController.php
src/Controller/PdfController.php
src/EventListener/CacheListener.php
src/Helper/Asset/AssetHelperRuntime.php
src/Helper/Cache/CacheHelper.php
src/Helper/Cache/CacheResponse.php
src/Helper/Request/EmschRequest.php
src/Helper/Request/EmschRequestResolver.php
src/Helper/Request/Handler.php
src/Helper/Routing/Router.php
src/Resources/config/local.xml
src/Resources/config/routing.xml
src/Resources/config/services.xml

build: 3.7.29

---

src/Helper/Elasticsearch/Settings.php

build: hotfix for 3.8.0

---

doc/twig.md
src/Controller/EmbedController.php
src/Resources/config/services.xml

Fragment function in embed controller

feat: fragment controller function

---

doc/twig.md
src/Controller/EmbedController.php
src/Helper/Local/Status/Item.php
src/Helper/Templating/TemplateFile.php
src/Resources/config/services.xml

build: 3.8.2

---

doc/search.md
src/Controller/SpreadsheetController.php
src/Helper/Search/Filter.php

build: 3.8.4

---

doc/routing.md

build: 3.8.5

---

composer.json
doc/routing.md

Allow Common 2.0 and force to stay in Symfony 4.4

build: 3.8.6

---

src/Command/Local/AbstractLocalCommand.php
src/Command/Local/PushCommand.php

Add a force option to emsch:local:push command

chore: force push

---

src/Command/Local/AbstractLocalCommand.php
src/Command/Local/PushCommand.php

#Feature
- #334 
force push for local command

build: 3.8.7

---

doc/twig.md
src/Controller/EmbedController.php

Allow the have cacheable sub items in twig

feat: cacheableFragment

---

doc/twig.md
src/Controller/EmbedController.php

build: 3.8.12

---

src/Helper/Search/Filter.php
src/Helper/Search/QueryBuilder.php

fix: postfiltering search

---

composer.json

Solve issue to run npm with the docker image: docker run --rm -it -u $(id -u ${USER}):$(id -g ${USER}) -v $PWD:/opt/src --workdir /opt/src elasticms/base-php-dev npm $@

fix: npm with docker

---

doc/Twig/functions.md
src/Helper/Elasticsearch/ClientRequest.php
src/Helper/Elasticsearch/ClientRequestRuntime.php
src/Helper/Environment/EnvironmentHelper.php
src/Twig/HelperExtension.php

emsch_add_environment function to load and environment in actions and templates

feat: emsch add environment

---

composer.json
doc/Twig/functions.md
src/Helper/Elasticsearch/ClientRequest.php
src/Helper/Elasticsearch/ClientRequestRuntime.php
src/Helper/Environment/EnvironmentHelper.php
src/Helper/Search/Filter.php
src/Helper/Search/QueryBuilder.php
src/Twig/HelperExtension.php

build: 3.10.0

---

src/Command/Local/UploadAssetsCommand.php

build: 3.10.1

---

doc/routing.md
src/Controller/RouterController.php

feat: allow the redirect controller method to throw a 404 exception

---

doc/routing.md
src/Controller/RouterController.php

build: 3.11.0

---

src/Helper/Routing/Router.php

build: 4.1.0
