ems-project/EMSClientHelperBundle

Elasticsearch/ClientRequest.php

php.CRITICAL: Fatal Error: Class 'EMS\ClientHelperBundle\Elasticsearch\Exception' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Class 'EMS\\ClientHelperBundle\\Elasticsearch\\Exception' not found at C:\\xampp\\htdocs\\ehealthportal\\contrib\\src\\vendor\\elasticms\\client-helper-bundle\\Elasticsearch\\ClientRequest.php:76)"}

BUGFIX: fatal error exception not found

---

Resources/config/services.xml

PHP Fatal error:  Uncaught exception
'Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException'
with message 'The service "emsch.twig.extension.routing" has a
dependency on a non-existent parameter

BUGFIX: missing parameter in services.xml

---

EMSBackendBridgeBundle/Service/RequestService.php

Use getLocale() instead of get('_locale')

Fix getting locale from symfony request

---

EMSBackendBridgeBundle/Elasticsearch/ClientRequest.php

1. By default unlimited depth search
2. do not check empty _source in array, but empty array itself.

Hierarchy bugfix sourceField

---

EMSBackendBridgeBundle/Controller/ApiController.php

Catchable Fatal Error: Argument 3 passed to
EMS\ClientHelperBundle\EMSBackendBridgeBundle\Service\ApiService::getContentType()
must be of the type array, null given, called in
elasticms\client-helper-bundle\EMSBackendBridgeBundle\Controller\ApiController.php on line 43 and defined

Bugfix: api controller

---

Controller/RouterController.php
Helper/Routing/RedirectHelper.php
Helper/Routing/Url/Transformer.php
Helper/Twig/TwigException.php
Helper/Twig/TwigLoader.php

If we forget defining EMSCH_TEMPLATES we just recieved an empty
response. Now when there is something wrong with a emsch template
we throw a custom Twig Exception

Improve template error messages

---

Controller/LanguageSelectController.php
Controller/SearchController.php
DependencyInjection/Configuration.php
DependencyInjection/EMSClientHelperExtension.php
EventListener/KernelListener.php
Helper/Request/ExceptionHelper.php
Helper/Routing/BaseRouter.php
Helper/Routing/EMSRouter.php
Helper/Routing/Router.php
Resources/config/services.xml

Added new Router for config/env routes -> search & language_select.
Otherwise these routers would be generated for each elasticms config.
New config reference:
ems_client_helper:
templates:
language: '%env(string:EMSCH_TEMPLATE_LANGUAGE)%'
search:   '%env(string:EMSCH_TEMPLATE_SEARCH)%'
error:    '%env(string:EMSCH_TEMPLATE_ERROR)%'

Add possibility for error templates

---

Helper/Translation/TranslationHelper.php
Resources/config/services.xml

Load all defined locales as the locale can be forced later in the translator functions. I.e.: {{ 'í18n.key'|trans({}, trans_default_domain, 'fr') }}

Load all defined locales as the locale can be forced later

---

Helper/Request/Environment.php
Helper/Request/RequestHelper.php

Implement the possibility to force the _locale based on the regex match.
Make it future prove so we can assign attributes dynamically.
Before:
EMSCH_ENVS='{"template": {"regex": "/.*/", "index": "template"}}'
After:
EMSCH_ENVS='{"template": {"regex": "/.*/", "request": {"_environment": "template", "_locale": "nl"} }}'

Improve request helper

---

Helper/Search/Filter.php
Helper/Search/QueryBuilder.php

- improve term search
- filter fields with %locale% should be replaced by the request locale
filter: {
"show": {
"type": "term",
"field": "show_%locale%",
"value": true,
"optional": true,
"public": false
}
}

bugfix: filtering %locale%

---

Helper/Search/Filter.php

They values provided to the date range are always converted to datetime
objects. But now we want to only search on documents that have a
datetime field in the past.

Improve search date range now

---

Helper/Search/Filter.php
Helper/Search/Manager.php
Helper/Search/QueryBuilder.php

When we use post filters we should also filter the aggregations.
This way the counts are always correct.
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/search-request-post-filter.html

Fix post filtering aggregations

---

Helper/Translation/TranslationHelper.php

When no translations keys are defined for a emsch_locale we get
ErrorException.

bugfix: undefined translation catalogue

---

Helper/Search/Filter.php
Helper/Search/Manager.php
Helper/Search/QueryBuilder.php
Helper/Search/Search.php

TODO: review the FILTER concept and use the 'non public' as default on
filters in the search class. QueryBuilder concepts should receive better
names, and the default filters should be accessible more easily (through
the SEARCH object)

urgent bugfix: use main query in aggregations

---

Helper/Search/Filter.php
phpstan-baseline.neon

Fix that a misformatted date generate a wrong elasticsearch query

hot(build query): misformatted date

---

Helper/Elasticsearch/ClientRequest.php

By defining the size in the query we may accept multiple results in route's query

hot(routing): allow a route's query to have more than one in total

---

DependencyInjection/EMSClientHelperExtension.php
Helper/Api/ApiService.php
Helper/Api/Client.php

|Bug fix?       |no|
|New feature?   |yes|	
|Fixed tickets  |no|	
Add 2 methods to the elasticms backend api client
- createFormVerification
- getFormVerification
Make getApiClient public on the ApiService:
The formBundle was not able to get the ApiClient.
Inject the Logger in the ApiService, for logging errors. In the future we should remove the Guzzle HttpClient and use the Symfony HttpClient

feat: api client form verification

---

DependencyInjection/EMSClientHelperExtension.php
Helper/Api/ApiService.php
Helper/Api/Client.php

|Bug fix?       |no|
|New feature?   |yes|	
|Fixed tickets  |no|	
Add 2 methods to the elasticms backend api client
- createFormVerification
- getFormVerification
Make getApiClient public on the ApiService:
The formBundle was not able to get the ApiClient.

release: 3.3.2

---

Helper/Search/Filter.php
phpstan-baseline.neon

|Bug fix?       |yes|
|New feature?   |no|	
|Fixed tickets  |no|	
We need to be able just passing 'now' as filter value, but for that we need to disable the date input formatting. 
You can now set the date_format of a filter config to false.

fix: search filter disable date format

---

Helper/Elasticsearch/ClientRequest.php

ScrollAll should use the clientRequest index.
Otherwise building all routes and translations in the cluster

fix: clientRequest scroll index

---

src/DependencyInjection/Configuration.php
src/DependencyInjection/EMSClientHelperExtension.php

|BC breaks?     |y|	
The clientHelper does not need the ElasticsearchLogger any more

fix: remove EMS\CommonBundle\Logger\ElasticsearchLogger

---

README.md

|New feature?   ||	
|BC breaks?     ||	
|Deprecations?  ||	
|Fixed tickets  ||	
Update the links to md doc files after the moves from /src/resources/doc to /doc

docs: fix doc file links

---

src/DependencyInjection/EMSClientHelperExtension.php
src/Helper/Routing/Url/Transformer.php
src/Resources/config/routing.xml

Refactor the url used for asset links in WYSIWYG field

refactor: use ems_asset_path to generate asset path (not hard coded url)

---

src/Helper/Routing/Route.php

until now it was not possible to specify multiple supported methods to a route like ['GET', 'POST']

feat: allow to define multiple supported methods to a route

---

doc/routing.md
doc/search.md
src/Helper/Search/Search.php

Allow route search_config as array (not only a JSON encoded string)

fix: search config as array
